### ISSUE TITLE
预训练中DOA_pretrain.py代码出现问题

### ISSUE THREAD

**Issue by colinzhaoxp** [gold-d/DOA#1]
您好，感谢您的贡献，更感谢您开源了代码。

您的工作非常有创新，我们想在此基础上开展工作。但是在预训练时，ODA_pretrain.py文件中的180行，使用了一个未先声明的变量：num_cate_index，导致代码运行错误。我尝试解决这个问题，但是没有思绪，您能解答一下吗？

同时在本文件的179行，有一个spa的变量计算出来，但是没有使用，请问这个变量有何作用呢？

非常期待您的回复。

**Comment by colinzhaoxp** [comment]
os.environ["OMP_NUM_THREADS"] = "1"
我注意到这行代码在预训练、训练和测试的文件中都存在，请问这行代码对于最终的性能有影响吗？
非常期待您的回复 ：)

**Comment by Rh-Dang** [comment]
非常感谢您对我们的研究感兴趣。

我们的DOA_pretrain.py中 的num_cate_index表示的是目标物体的one_hot编码，spa是场景中所有可能物体的one_hot编码。我们在DOA_pretrain.py中少添加了一行代码，如下：
'''
spa = self.one_hot(self.num_cate).to(target.device).view(1, self.num_cate, self.num_cate).expand(batch_size, self.num_cate, self.num_cate) 
num_cate_index = torch.bmm(spa.transpose(1, 2), target_object).transpose(1, 2)  
num_cate_index = self.num_cate_embed(num_cate_index)
'''
已经在仓库中更正，希望能够帮到您。

os.environ["OMP_NUM_THREADS"] = "1" 对于最终结果影响很小，可以忽视。

**Comment by colinzhaoxp** [comment]
非常感谢您的回复！！！

**Comment by colinzhaoxp** [comment]
您好，在您开源的项目中有一个已经训练好的模型，在我想使用这个模型来进行测试的时候，出现了一些错误：
![image](https://user-images.githubusercontent.com/48939690/204217771-96f10a48-2062-4464-8087-374ccf52a775.png)
进一步，我发现您提供的模型参数相比于DOA默认参数确实多了gcn_input、zones_feature、fuse_scale这三个参数。
![image](https://user-images.githubusercontent.com/48939690/204217496-fcaecaa1-cfab-4c82-a957-dcacab2f314d.png)
请问您当时是如何处理这三个参数的呢？
期待您的回复：）

**Comment by Rh-Dang** [comment]
这三个参数在我们最终的模型中是不需要，训练好的模型参数可能对应于旧版本的model文件，不能在新版本的model上测试。我们将在之后更新最新的模型参数。
我们建议您自己训练一个模型。两个2080Ti GPU只需要一天半的时间。

**Comment by colinzhaoxp** [comment]
谢谢您的回复，我主要是怕一些参数上的差异，导致自己训练的精度不是很高。
我会尝试自己训练一个，当然也期待您的发布新的模型。
